openapi: 3.0.1
info:
  title: BookStore
  description: ''
  termsOfService: http://swagger.io/terms/
  contact:
    email: izdebski.maciek@gmail.com
  version: 1.0.0
tags:
- name: book
  description: Everything about your Books
paths:
  /books:
    get:
      tags:
      - book
      summary: Get all books from database
      operationId: getAllBooks
      parameters:
      - name: name
        in: query
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Not found
          content: {}
          
  /books/{ISBN}:
    get:
      tags:
      - book
      operationId: getBook
      description: Get book by ISBN
      parameters:
      - name: ISBN
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        404:
          description: Not found
          content: {}
      
components:
  schemas:
    Book:
      type: object
      properties:
        ISBN:
          type: string
        name:
          type: string
        author:
          type: string
      xml:
        name: Book
